# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edc7fe3f24c3624ad6834520dff02d056b3df72592817d06a65e34b2abab1b5081e754a4562d5194e65d9e1c52f250f814c06672141a9e465e794bfd7331c513

test:
  secret_key_base: 6c3b6dd013487da4acb84b95da95eaa5d5a5cbfb485cbbefc87d0d8e667b8e7cbb2fc1b2bdaeb9796dd9e7369fb8d09b31498c60c8f85cc9a861731859f2f2c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
